// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using api.Database;

#nullable disable

namespace api.Migrations
{
    [DbContext(typeof(TrophyDbContext))]
    [Migration("20260516144022_SnakeCaseNamingConvention")]
    partial class SnakeCaseNamingConvention
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("api.Database.Models.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Emoji")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)")
                        .HasColumnName("emoji");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("ParentGroupId")
                        .HasColumnType("integer")
                        .HasColumnName("parent_group_id");

                    b.HasKey("Id")
                        .HasName("pk_games");

                    b.HasIndex("ParentGroupId", "Emoji")
                        .IsUnique()
                        .HasDatabaseName("ix_games_parent_group_id_emoji");

                    b.ToTable("games", (string)null);
                });

            modelBuilder.Entity("api.Database.Models.Group", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AdminId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("admin_id");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<int>("DecisionModel")
                        .HasColumnType("integer")
                        .HasColumnName("decision_model");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("ImageId")
                        .HasColumnType("text")
                        .HasColumnName("image_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_groups");

                    b.HasIndex("AdminId")
                        .HasDatabaseName("ix_groups_admin_id");

                    b.ToTable("groups", (string)null);
                });

            modelBuilder.Entity("api.Database.Models.GroupInvite", b =>
                {
                    b.Property<int>("GroupId")
                        .HasColumnType("integer")
                        .HasColumnName("group_id");

                    b.Property<DateTimeOffset>("ExpirationDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expiration_date");

                    b.Property<string>("InviteCode")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("invite_code");

                    b.Property<DateTimeOffset>("NextAllowedResetDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_allowed_reset_date");

                    b.HasKey("GroupId")
                        .HasName("pk_group_invites");

                    b.HasIndex("InviteCode")
                        .HasDatabaseName("ix_group_invites_invite_code");

                    b.ToTable("group_invites", (string)null);
                });

            modelBuilder.Entity("api.Database.Models.Trophy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset?>("AwardedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("awarded_date");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("GameId")
                        .HasColumnType("integer")
                        .HasColumnName("game_id");

                    b.Property<string>("ReceiverId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("receiver_id");

                    b.HasKey("Id")
                        .HasName("pk_trophies");

                    b.HasIndex("GameId")
                        .HasDatabaseName("ix_trophies_game_id");

                    b.HasIndex("ReceiverId")
                        .HasDatabaseName("ix_trophies_receiver_id");

                    b.ToTable("trophies", (string)null);
                });

            modelBuilder.Entity("api.Database.Models.TrophyRequest", b =>
                {
                    b.Property<int>("TrophyId")
                        .HasColumnType("integer")
                        .HasColumnName("trophy_id");

                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.HasKey("TrophyId")
                        .HasName("pk_trophy_requests");

                    b.ToTable("trophy_requests", (string)null);
                });

            modelBuilder.Entity("api.Database.Models.TrophyRequestApproval", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.Property<int>("RequestId")
                        .HasColumnType("integer")
                        .HasColumnName("request_id");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("boolean")
                        .HasColumnName("is_approved");

                    b.HasKey("UserId", "RequestId")
                        .HasName("pk_trophy_request_approvals");

                    b.HasIndex("RequestId")
                        .HasDatabaseName("ix_trophy_request_approvals_request_id");

                    b.ToTable("trophy_request_approvals", (string)null);
                });

            modelBuilder.Entity("api.Database.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("first_name");

                    b.Property<string>("ImageId")
                        .HasColumnType("text")
                        .HasColumnName("image_id");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("last_name");

                    b.Property<string>("MiddleName")
                        .HasColumnType("text")
                        .HasColumnName("middle_name");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Id")
                        .HasDatabaseName("ix_users_id");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("api.Database.Models.UserGroup", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.Property<int>("GroupId")
                        .HasColumnType("integer")
                        .HasColumnName("group_id");

                    b.Property<DateTimeOffset>("JoinedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("joined_at");

                    b.HasKey("UserId", "GroupId")
                        .HasName("pk_user_groups");

                    b.HasIndex("GroupId")
                        .HasDatabaseName("ix_user_groups_group_id");

                    b.ToTable("user_groups", (string)null);
                });

            modelBuilder.Entity("api.Database.Models.Game", b =>
                {
                    b.HasOne("api.Database.Models.Group", "ParentGroup")
                        .WithMany("Games")
                        .HasForeignKey("ParentGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_games_groups_parent_group_id");

                    b.Navigation("ParentGroup");
                });

            modelBuilder.Entity("api.Database.Models.Group", b =>
                {
                    b.HasOne("api.Database.Models.User", "Admin")
                        .WithMany()
                        .HasForeignKey("AdminId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_groups_users_admin_id");

                    b.Navigation("Admin");
                });

            modelBuilder.Entity("api.Database.Models.GroupInvite", b =>
                {
                    b.HasOne("api.Database.Models.Group", "Group")
                        .WithOne("Invite")
                        .HasForeignKey("api.Database.Models.GroupInvite", "GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_group_invites_groups_group_id");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("api.Database.Models.Trophy", b =>
                {
                    b.HasOne("api.Database.Models.Game", "Game")
                        .WithMany("Trophies")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_trophies_games_game_id");

                    b.HasOne("api.Database.Models.User", "Receiver")
                        .WithMany("Trophies")
                        .HasForeignKey("ReceiverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_trophies_users_receiver_id");

                    b.Navigation("Game");

                    b.Navigation("Receiver");
                });

            modelBuilder.Entity("api.Database.Models.TrophyRequest", b =>
                {
                    b.HasOne("api.Database.Models.Trophy", "Trophy")
                        .WithOne("Request")
                        .HasForeignKey("api.Database.Models.TrophyRequest", "TrophyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_trophy_requests_trophies_trophy_id");

                    b.Navigation("Trophy");
                });

            modelBuilder.Entity("api.Database.Models.TrophyRequestApproval", b =>
                {
                    b.HasOne("api.Database.Models.TrophyRequest", "Request")
                        .WithMany("Approvals")
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_trophy_request_approvals_trophy_requests_request_id");

                    b.HasOne("api.Database.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_trophy_request_approvals_users_user_id");

                    b.Navigation("Request");

                    b.Navigation("User");
                });

            modelBuilder.Entity("api.Database.Models.UserGroup", b =>
                {
                    b.HasOne("api.Database.Models.Group", "Group")
                        .WithMany("UserGroups")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_groups_groups_group_id");

                    b.HasOne("api.Database.Models.User", "User")
                        .WithMany("UserGroups")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_groups_users_user_id");

                    b.Navigation("Group");

                    b.Navigation("User");
                });

            modelBuilder.Entity("api.Database.Models.Game", b =>
                {
                    b.Navigation("Trophies");
                });

            modelBuilder.Entity("api.Database.Models.Group", b =>
                {
                    b.Navigation("Games");

                    b.Navigation("Invite");

                    b.Navigation("UserGroups");
                });

            modelBuilder.Entity("api.Database.Models.Trophy", b =>
                {
                    b.Navigation("Request")
                        .IsRequired();
                });

            modelBuilder.Entity("api.Database.Models.TrophyRequest", b =>
                {
                    b.Navigation("Approvals");
                });

            modelBuilder.Entity("api.Database.Models.User", b =>
                {
                    b.Navigation("Trophies");

                    b.Navigation("UserGroups");
                });
#pragma warning restore 612, 618
        }
    }
}
