set dotenv-load
set dotenv-path := "backend/api/.env"

# ── Backend ──────────────────────────────────────────────

# Build the backend solution
build-backend:
    dotnet build backend/trophy-tracker.sln

# Run backend tests
test-backend:
    dotnet test backend/trophy-tracker.sln

# Start the backend API server
run-backend:
    dotnet run --project backend/api

# ── Frontend ─────────────────────────────────────────────

# Start frontend dev server (Relay watch + Vite)
dev-frontend:
    npm run dev --prefix frontend

# Production build of frontend
build-frontend:
    npm run build --prefix frontend

# ── Cross-cutting ────────────────────────────────────────

# Export GraphQL schema from backend
schema-export:
    dotnet run --project backend/api schema export --output schema.graphql
    cp backend/api/schema.graphql backend/api/API/schema.graphql

# Run Relay compiler
relay:
    cd frontend && npx relay-compiler

# Fail if canonical and API-local schema files drift
check-schema-drift:
    diff -u backend/api/schema.graphql backend/api/API/schema.graphql

# Full schema update pipeline: export → relay codegen → snapshot
update-schema: schema-export relay update-snapshot

# Update schema snapshot test
update-snapshot:
    node -e "const fs=require('fs');const s=fs.readFileSync('backend/api/schema.graphql','utf8').replace(/\n$/,'');fs.writeFileSync('backend/tests/GraphQL/_snapshots/SchemaShould_HaveNoUnconfirmedChanges.json', JSON.stringify({AutoGenerated:s}, null, 2)+'\\n');"

# ── Infrastructure ───────────────────────────────────────

# Start PostgreSQL via Docker Compose (dev: exposes 5432 on 127.0.0.1)
db-up:
    docker compose -f docker-compose.yml -f docker-compose.dev.yml up -d db

# Stop PostgreSQL
db-down:
    docker compose -f docker-compose.yml -f docker-compose.dev.yml down db

# Run EF Core migration (usage: just migrate AddNewTable)
migrate name:
    dotnet ef migrations add {{name}} --project backend/api

# Apply pending migrations
db-update:
    dotnet ef database update --project backend/api

# Seed the dev database with realistic test data (usage: just db-seed user_xxxx)
db-seed user-id:
    dotnet run --project backend/api -- seed {{user-id}}

# ── Full stack ───────────────────────────────────────────

# Start everything for local development
dev: db-up run-backend dev-frontend
